# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-27 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswers',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswers',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
